import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';

import useServerDarkMode from '../hooks/use-server-dark-mode';

import Providers from '../providers/providers';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: LayoutProps<'/'>) {
  const theme = await useServerDarkMode();

  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${theme === 'dark' ? 'dark' : ''} `}
    >
      <body className='flex flex-col min-h-screen bg-white text-black dark:bg-slate-950 dark:text-slate-100 px-8'>
        <Providers>
          <div className='flex flex-col mx-auto w-full max-w-4xl'>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
